version: '3.9'
services:

  service-registry:
    image: 'rohit7978/service-registry'
    container_name: service-registry
    ports:
      - '8761:8761'

  config-server:
    image: 'rohit7978/config-server'
    container_name: config-server
    ports:
      - '9296:9296'
    environment:
      - EUREKA_DOCKER_HOST=http://service-registry:8761/eureka
    healthcheck:
      test: [ "CMD","curl","-f","http://config-server:9296/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - service-registry

  cloud-api-gateway:
    image: 'rohit7978/cloud-api-gateway'
    container_name: cloud-api-gateway
    ports:
      - '9090:9090'
    environment:
      - EUREKA_DOCKER_HOST=http://service-registry:8761/eureka
      - CONFIG_DOCKER=config-server
    depends_on:
      config-server:
        condition: service_healthy

  order-service:
    image: 'rohit7978/order-service'
    container_name: order-service
    ports:
      - '8081:8081'
    environment:
      - EUREKA_DOCKER_HOST=http://service-registry:8761/eureka
      - CONFIG_DOCKER=config-server
      - DB_HOST=host.docker.internal
    depends_on:
      config-server:
        condition: service_healthy

  product-service:
    image: 'rohit7978/product-service'
    container_name: product-service
    ports:
      - '8080:8080'
    environment:
      - EUREKA_DOCKER_HOST=http://service-registry:8761/eureka
      - CONFIG_DOCKER=config-server
      - DB_HOST=host.docker.internal
    depends_on:
      config-server:
        condition: service_healthy


  payment-service:
    image: 'rohit7978/payment-service'
    container_name: payment-service
    ports:
      - '8082:8082'
    environment:
      - EUREKA_DOCKER_HOST=http://service-registry:8761/eureka
      - CONFIG_DOCKER=config-server
      - DB_HOST=host.docker.internal
    depends_on:
      config-server:
        condition: service_healthy