server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: rohit7978
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ORDER-SERVICE

  config:
    import: configserver:http://localhost:9296

product:
  service:
    url: http://localhost:8080
    name: PRODUCT-SERVICE
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

